### ISSUE TITLE
DeepFace-EMD for ViT

### ISSUE THREAD

**Issue by mnikitin** [anguyen8/deepface-emd#7]
Hello!

Have you tried to use EMD with image features produced by visual transformer?
Looks like the last transformer layer of typical ViT outputs embeddings for each image patch, which is similar to the conv-features you use in the paper.

Is there any disadvantages to use such transformer features in your DeepFace-EMD method?
The only difference I see is that patch embeddings in ViT interact with each other throughout the whole image because of the attention mechanism, while conv-features are more local.

Thank you!

**Comment by anguyen8** [comment]
Thank you for your question!

No, we have not tried using ViT patch embeddings. But yes, you could try it with our DeepFace-EMD formulation.
Based on my experience outside of this project, patch embeddings contain more context than CNN features (as you said) so that at some point, you may actually lose the interpretability of what a patch embedding represents, and so the interpretability/utility of the heatmap.

**Comment by anguyen8** [comment]
@mnikitin Furthermore, it depends on how you use ViT. 

If you use cross-attention between two images, then it's not practical to cache the ViT features of every pair of images.
If you only have self-attention, then that's OK.
